'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, MessageCircle, Star } from 'lucide-react';
import { authenticatedFetch, responseError } from '@/lib/client-api';
import { notify } from '@/lib/toast';
import type { ActivityItem } from '@/lib/discussions';
export default function ActivityPanel(){const[items,setItems]=useState<ActivityItem[]>([]);const[loading,setLoading]=useState(true);const[sort,setSort]=useState<'newest'|'oldest'>('newest');useEffect(()=>{authenticatedFetch('/api/activity').then(async(response)=>{if(!response.ok)throw new Error(await responseError(response,'Unable to load activity.'));return response.json()}).then((result)=>setItems(result.items)).catch((error)=>notify(error instanceof Error?error.message:'Unable to load activity.','error')).finally(()=>setLoading(false))},[]);const sorted=useMemo(()=>[...items].sort((a,b)=>(new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())*(sort==='newest'?1:-1)),[items,sort]);return <section className='motion-content py-8 md:py-5'><div className='flex items-end justify-between gap-5'><div><p className='font-inter text-xs uppercase tracking-[0.18em] font-extralight'>Community activity</p><h2 className='font-lora text-3xl md:text-2xl mt-2'>Your activity</h2></div><div className='flex border border-foreground/15 p-1 font-inter text-[10px] uppercase tracking-wider'><button onClick={()=>setSort('newest')} className={`px-3 py-2 ${sort==='newest'?'bg-foreground text-background':''}`}>Newest</button><button onClick={()=>setSort('oldest')} className={`px-3 py-2 ${sort==='oldest'?'bg-foreground text-background':''}`}>Oldest</button></div></div><div className='mt-6'>{loading?<ActivitySkeleton/>:sorted.length?<div className='space-y-2'>{sorted.map((item)=><Link key={`${item.kind}-${item.id}`} href={item.href} className='group grid grid-cols-[auto_1fr_auto] items-start gap-4 bg-foreground/4 p-4'><span className='mt-0.5'>{item.kind.startsWith('review')?<Star size={16} fill={item.rating?'currentColor':'none'}/>:<MessageCircle size={16}/>}</span><span className='min-w-0'><span className='flex flex-wrap items-center gap-x-3 gap-y-1 font-inter text-[10px] uppercase tracking-wider opacity-55'><span>{item.kind.replace('-',' ')}</span><time>{new Date(item.createdAt).toLocaleString()}</time></span><strong className='mt-2 block truncate font-lora text-sm font-normal'>{item.chapterTitle||item.novelTitle}</strong><span className='mt-1 block truncate font-inter text-xs font-extralight opacity-70'>{item.body}</span></span><ArrowUpRight size={15} className='transition-transform group-hover:translate-x-1 group-hover:-translate-y-1'/></Link>)}</div>:<p className='py-16 text-center font-inter text-sm font-extralight opacity-55'>Your reviews and comments will appear here.</p>}</div></section>}
function ActivitySkeleton(){return <div className='space-y-2'>{[0,1,2].map((item)=><div key={item} className='bg-foreground/4 p-4'><span className='skeleton block h-3 w-40'/><span className='skeleton block h-5 w-1/3 mt-3'/><span className='skeleton block h-3 w-3/4 mt-3'/></div>)}</div>}

