'use client';
import { useEffect, useRef, useSyncExternalStore } from 'react';
import { Moon, Sun } from 'lucide-react';
import { useTheme } from 'next-themes';
import type { ReaderSettings, ReaderTheme } from '@/types/reader';
import { READER_SETTINGS_STORAGE_KEY } from '@/lib/constants';

type Props={initialSettings?:ReaderSettings;authenticated?:boolean;variant?:'floating'|'account';syncInitial?:boolean;onThemeChange?:(theme:ReaderTheme)=>void};
const subscribe=()=>()=>{};
export default function ThemeToggle({initialSettings,authenticated=false,variant='floating',syncInitial=false,onThemeChange}:Props){const mounted=useSyncExternalStore(subscribe,()=>true,()=>false);const synced=useRef(false);const{resolvedTheme,setTheme}=useTheme();useEffect(()=>{if(synced.current||!syncInitial||!authenticated||!initialSettings)return;synced.current=true;setTheme(initialSettings.theme);localStorage.setItem(READER_SETTINGS_STORAGE_KEY,JSON.stringify(initialSettings))},[syncInitial,authenticated,initialSettings,setTheme]);if(!mounted)return variant==='floating'?null:<div className='h-14 border border-foreground/10'/>;const dark=resolvedTheme==='dark';async function toggle(){const next:ReaderTheme=dark?'light':'dark';setTheme(next);onThemeChange?.(next);window.dispatchEvent(new CustomEvent('monochrome-theme-change',{detail:next}));let settings=initialSettings;const saved=localStorage.getItem(READER_SETTINGS_STORAGE_KEY);if(saved)try{settings=JSON.parse(saved)}catch{}if(settings){const updated={...settings,theme:next};localStorage.setItem(READER_SETTINGS_STORAGE_KEY,JSON.stringify(updated));if(authenticated)await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(updated)})}}
  if(variant==='account')return <button onClick={toggle} aria-label={`Switch to ${dark?'light':'dark'} mode`} className='w-full min-h-14 flex items-center justify-between border border-foreground/15 bg-foreground/[0.035] px-5 font-inter text-sm font-light cursor-pointer transition-colors hover:bg-foreground/[0.07]'><span className='flex items-center gap-3'>{dark?<Moon size={18}/>:<Sun size={18}/>}<span>{dark?'Dark mode':'Light mode'}</span></span><span aria-hidden className='relative block w-11 h-6 shrink-0 border border-foreground/20 bg-background'><span className={`absolute left-0 top-[3px] size-4 bg-foreground transition-transform duration-200 ${dark?'translate-x-[22px]':'translate-x-1'}`}/></span></button>;
  return <button aria-label={`Switch to ${dark?'light':'dark'} mode`} title={`Switch to ${dark?'light':'dark'} mode`} onClick={toggle} className='hidden md:grid fixed left-7 bottom-7 z-40 size-11 place-items-center border border-foreground/15 bg-background/80 shadow-lg backdrop-blur cursor-pointer'>{dark?<Sun size={19}/>:<Moon size={19}/>}</button>;
}
