'use client';
import { useState } from 'react';
import { X } from 'lucide-react';
import useAnimatedPresence from '@/hooks/useAnimatedPresence';
import { authenticatedFetch, responseError } from '@/lib/client-api';
import { notify } from '@/lib/toast';
export default function UsernameDialog({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (username: string) => void }) {
  const presence = useAnimatedPresence(open ? true : null); const [username,setUsername]=useState(''); const [pending,setPending]=useState(false); const [error,setError]=useState('');
  async function save(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(''); try { const response=await authenticatedFetch('/api/profile/username',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({username})}); if(!response.ok) throw new Error(await responseError(response,'Unable to save username.')); const result=await response.json(); notify('Username saved.','success'); onSaved(result.username); onClose(); } catch(error){setError(error instanceof Error?error.message:'Unable to save username.')} finally{setPending(false)} }
  if(!presence.mounted)return null; return <div className='fixed inset-0 z-[110] grid place-items-center px-5'><button data-motion-state={presence.state} aria-label='Close username dialog' onClick={onClose} className='motion-overlay absolute inset-0 bg-black/45 backdrop-blur-sm cursor-default'/><form data-motion-state={presence.state} onSubmit={save} role='dialog' aria-modal='true' aria-labelledby='username-title' className='motion-dialog relative z-10 w-full max-w-md border border-foreground/15 bg-background p-7 text-foreground shadow-2xl'><button type='button' aria-label='Close' onClick={onClose} className='absolute right-5 top-5 cursor-pointer'><X size={18}/></button><p className='font-inter text-[10px] uppercase tracking-[0.2em] font-extralight'>Your public identity</p><h2 id='username-title' className='font-lora text-3xl mt-3'>Choose a username</h2><p className='font-inter text-sm font-extralight leading-6 mt-4'>This name appears beside your reviews, comments, and replies. You can change it later in your account.</p><label className='block font-inter text-xs uppercase tracking-widest mt-7' htmlFor='dialog-username'>Username</label><input autoFocus id='dialog-username' value={username} onChange={(event)=>setUsername(event.target.value)} minLength={3} maxLength={24} pattern='[A-Za-z0-9_]+' required className='mt-3 w-full border-b border-foreground/20 bg-transparent py-3 font-inter'/>{error&&<p role='alert' className='mt-4 text-sm text-red-500'>{error}</p>}<button disabled={pending} className='mt-7 w-full bg-foreground px-5 py-3 font-inter text-xs text-background disabled:opacity-50'>{pending?'Saving…':'Save username'}</button></form></div>;
}
